protected/controllers/RssearchController.php
<?php

/**
 * Class RssearchController
 * @var $p Peoplesearch
 */
class RssearchController extends Controller
{
    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }
    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('deny', // allow all users to perform 'index' and 'view' actions
                'users' => array('?'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'users' => array('@'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }
    public function actionIndex()
    {
        $p = Peoplesearch::model();
        $p->setAttributes(@$_POST['Peoplesearch']);

        $r = Reestrsearch::model();
        $r->setAttributes(@$_POST['Reestrsearch']);

        $res = $p->sqlsearch($r);
        $peoplesDataProvider = $res[0];
        $mes = $res[1];
        foreach($mes as $k=>$v)
        {
            Yii::app()->user->setFlash($k,$v);
        }

        $this->render('index', array('peoplemodel' => $p, 'reestrmodel' => $r, 'dataProvider' => $peoplesDataProvider,));
    }

    public function actionAjaxsearch()
    {
        $p = new Peoplesearch();
        $p->setAttributes(@$_POST['Peoplesearch']);

        $r = new Reestrsearch();
        $r->setAttributes(@$_POST['Reestrsearch']);

        $res = $p->sqlsearch($r);
        $peoplesDataProvider = $res[0];
        $mes = $res[1];
        foreach($mes as $k=>$v)
        {
            Yii::app()->user->setFlash($k,$v);
        }
        $this->renderPartial('application.views.rssearch._result_list', array('dataProvider'=>$peoplesDataProvider), false, true);
    }
}

protected/views/rssearch/_result_list.php
<?php
/**

 * User: Локтионов_АВ
 * Date: 04.07.14
 * Time: 14:50
 * @var $this RssearchController
 * @var $dataProvider CArrayDataProvider
 */
?>

<?php
foreach (Yii::app()->user->getFlashes(false) as $key => $message) {

    echo TbHtml::alert($key, $message);
}
?>
<?php if (isset($dataProvider)) { ?>
    <?php
    $this->widget('TbListView', array(
        'id' => 'rssearch-listview',
        'dataProvider' => $dataProvider,
        'itemView' => 'application.views.rssearch.view',
        'template' => '{summary} {pager} {items}',
        'summaryText' => 'Найдено: {count}'
    ));
} ?>

protected/views/rssearch/_search_form.php
<div class="search-form">
    <?php
    /* @var $peoplemodel Peoplesearch */
    /* @var $reestrmodel Reestrsearch */
    /* @var $form TbActiveForm */
    $form = $this->beginWidget('TbActiveForm', array(
        'id' => 'search-form',
        'method' => 'post',
        // Please note: When you enable ajax validation, make sure the corresponding
        // controller action is handling ajax validation correctly.
        // There is a call to performAjaxValidation() commented in generated controller code.
        // See class documentation of CActiveForm for details on this.
        'enableAjaxValidation' => false,
    ));

    ?>


    <div class="cell">
        <div class="cell">
            <?php echo $form->textFieldControlGroup($peoplemodel, 'sName', array('placeholder' => 'Фамилия',)); ?>
        </div>

        <div class="cell">
            <?php echo $form->textFieldControlGroup($peoplemodel, 'Name', array('placeholder' => 'Имя',)); ?>
        </div>
    </div>
    <div class="cell">
        <div class="cell">
            <?php echo $form->textFieldControlGroup($peoplemodel, 'pName', array('placeholder' => 'Отчество',)); ?>
        </div>

        <div class="cell">
            <label class="control-label" for="Peoplesearch_dateMan">Дата рождения</label>
            <?php $form->widget('zii.widgets.jui.CJuiDatePicker', array(
                    'language' => 'ru',
                    'model' => $peoplemodel,
                    'attribute' => 'dateMan',
                    'htmlOptions' => array(
                        'placeholder' => 'Дата рождения',
                        'style' => 'min-width: inherit ! important;'
                    ),
                )
            ); ?>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="cell">
        <label class="control-label" for="Peoplesearch_ENP">ЕНП</label>
        <?php $this->widget('CMaskedTextField', array(
            'model' => $peoplemodel,
            'attribute' => 'ENP',
            'placeholder' => '',
            'mask' => '0000000000000000',
            'htmlOptions' => array(
                'size' => 40,
                'placeholder' => 'ЕНП',
            ),

        ));?>
        <?php echo $form->error($peoplemodel, 'ENP'); ?>
    </div>
    <div class="cell">
        <?php echo $form->textFieldControlGroup($reestrmodel, 'ENumber', array(
            'size' => 40,
            'maxlength' => 40,
            'placeholder' => 'Полис',
        )); ?>
    </div>

    <div class="clear"></div>

    <div class="cell">
        <?php echo TbHtml::ajaxSubmitButton('Найти', Yii::app()->createAbsoluteUrl('rssearch/ajaxsearch'), array(
            'success' => new CJavaScriptExpression('function(html){$("#result_list").html(html)}'),
        ), array(
            //'size' => TbHtml::BUTTON_SIZE_LARGE,
            'color' => TbHtml::BUTTON_COLOR_WARNING,
            'onclick' => new CJavaScriptExpression('SetLoadingIndicator()'),
        )); ?>
    </div>
    <?php echo TbHtml::link('Очистить', 'javascript:void(0)', array(
        'class' => 'java-link pull-right',
        'style' => 'padding-top: 20px;',
        'onclick' => new CJavaScriptExpression('ClearInputs();'),
    )); ?>

    <?php $this->endWidget(); ?>


</div>

<script type="text/javascript">
    function ClearInputs() {
        var sname = $('#Peoplesearch_sName').val('');
        var name = $('#Peoplesearch_Name').val('');
        var pname = $('#Peoplesearch_pName').val('');
        var dateman = $('#Peoplesearch_dateMan').val('');
        var enp = $('#Peoplesearch_ENP').val('');
        var enumber = $('#Reestrsearch_ENumber').val('');
    }
    function SetLoadingIndicator() {
        $("#result_list").html('<img src="/css/ajax-loader.gif">');
    }
</script>

protected/views/rssearch/index.php
<?php
/**
 * @var $this RssearchController
 * @var $peoplemodel Peoplesearch
 * @var $reestrmodel Reestrsearch
 * @var $dataProvider CArrayDataProvider
 * */ ?>


<?php $this->breadcrumbs = array(
    'Поиск',
);
?>
    <?php $this->renderPartial('application.views.rssearch._search_form', array(
        'peoplemodel'=>$peoplemodel,
        'reestrmodel'=>$reestrmodel
    )); ?>
<div id="result_list">
<?php $this->renderPartial('application.views.rssearch._result_list', array(
    'dataProvider'=>$dataProvider,
)); ?>
</div>

protected/views/rssearch/view.php
<?php
/**
 * User: Локтионов_АВ
 * Date: 04.07.14
 * Time: 17:07
 * @var $data People
 */
?>
<div style="float: left; width: 30%; margin: 0 15px 15px 15px;">
    <span
        class="cat"><?php echo $data->ENP . ' ' . Helpers::GetSex($data->sexMan) . ' ' . date(Helpers::getDateFormat(), strtotime($data->dateMan)); ?></span>
    <br/>
    <?php echo $data->sName . ' ' . $data->Name . ' ' . $data->pName; ?>
</div>
<div style="float: left;width:30%;margin-right: 10px;">
    <?php foreach ($data->reestrs as $r) { ?>
        <?php


        if (!empty($r->org)) {
            echo $r->org->NAMSMO;
        } else {
            echo '';
        }


        ?>
        <br/>
        <?php echo $r->ENumber; ?>
        <?php break; ?>
    <?php } ?>
</div>
<?php
$params[] = $data->sName;
$params[] = $data->Name;
$params[] = $data->pName;
$params[] = $data->sexMan;
$params[] = date(Helpers::getDateFormat(), strtotime($data->dateMan));
$params[] = $data->contact;
$params[] = empty($data->reestrs) ? '' : $data->reestrs[0]->typePoles;
$params[] = empty($data->reestrs) ? '' : $data->reestrs[0]->ENumber;
$params[] = Yii::app()->params['okato'];
/** @var $reestr Reestr */
$reestr = Reestr::model()->find('manid=:manid and statuspoles > 0', array(':manid'=>$data->id));
$params[] = empty($reestr) ? '' :   $reestr->org->KODSMO;
foreach ($params as $k => $v) {
    $params[$k] = '"' . trim($v) . '"';
}
$str_params = implode(',', $params);
echo TbHtml::link('Открыть', '#form_tab', array(
    'onclick' => new CJavaScriptExpression("SetZL($str_params)"),
    'data-toggle' => 'tab',
    'tab-index' => "-1",
    'role' => 'tab',
));
?>
<hr>